sudo: required
services:
        - docker

before_install:
        - docker build -t devopstank/docker-react -f Dockerfile.dev .

script:
        - docker run devopstank/docker-react npm run test -- --coverage     
